"use server";

import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { isPro } from "@/lib/entitlements";
import { checkUploadAccess } from "@/lib/uploadGate";
import { FREE_UPLOAD_LIMIT_PER_CLAIM } from "@/lib/uploadLimits";
import {
  isGuaranteeChecklistKey,
  setGuaranteeChecklistItem,
  finalizeGuaranteeIfComplete,
} from "@/lib/guarantee";
import { checklistTemplateFor } from "@/lib/scoring/checklistTemplates";
import { isAllowedUpload } from "@/lib/uploadValidation";
import { checkClaimCategoryAccess, getCategoryClaimState, type ClaimCategoryGateResult } from "@/lib/claimCategoryGate";
import { isClaimCategory, isClaimStatus, type ClaimCategory } from "@/lib/claimCategories";
import { isEvidenceStage } from "@/lib/evidenceStage";

export async function signOut() {
  const supabase = await createClient();
  await supabase.auth.signOut();
  redirect("/login");
}

export async function createClaim(formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const carrier = String(formData.get("carrier") ?? "").trim() || null;
  const claim_number = String(formData.get("claim_number") ?? "").trim() || null;
  const policy_number = String(formData.get("policy_number") ?? "").trim() || null;
  const date_of_loss = String(formData.get("date_of_loss") ?? "").trim() || null;
  const date_discovered = String(formData.get("date_discovered") ?? "").trim() || null;
  const damage_category = String(formData.get("damage_category") ?? "").trim() || null;
  const damage_desc = String(formData.get("damage_desc") ?? "").trim() || null;
  const us_state = String(formData.get("us_state") ?? "").trim() || null;

  // Decision #75 -- required going forward, re-validated here regardless of
  // ClaimWizard.tsx's own client-side check, same discipline every other
  // gate in this file follows.
  const label = String(formData.get("label") ?? "").trim();
  if (!label) {
    throw new Error("Give this claim a short label before continuing.");
  }

  const claim_category_raw = String(formData.get("claim_category") ?? "").trim();
  if (!isClaimCategory(claim_category_raw)) {
    throw new Error("Choose a dispute category to continue.");
  }
  const claim_category: ClaimCategory = claim_category_raw;

  // Free-plan claim limits, category-based (Decision #44). Re-checked here
  // server-side regardless of any earlier client-side check the wizard
  // already did — never trust a prior round trip, same discipline every
  // other gate in this codebase follows (checkUploadAccess, checkUsageGate).
  const gate = await checkClaimCategoryAccess(supabase, user.id, claim_category);
  if (!gate.allowed) {
    throw new Error(
      "You already have a claim on file for this category. Upgrade to WholeClaim Pro to manage unlimited property documentation workflows, or continue your existing claim.",
    );
  }

  const { data, error } = await supabase
    .from("claims")
    .insert({
      user_id: user.id,
      carrier,
      claim_number,
      policy_number,
      date_of_loss,
      date_discovered,
      damage_category,
      damage_desc,
      us_state,
      claim_category,
      label,
    })
    .select("id")
    .single();

  if (error || !data) {
    throw new Error(error?.message ?? "Could not create claim.");
  }

  // Documentation Score checklist seeding (Decision #40, Option 1 — new
  // claims only, never a retroactive backfill). Best-effort: a claim with
  // zero checklist rows just scores 0 on Evidence Coverage / Documentation
  // Completeness until the user adds items manually, same as before this
  // existed, so a failure here must never block claim creation itself.
  //
  // available_labels (Onboarding Step 4, Claim Creation Wizard): a
  // JSON-encoded array of checklist item labels the user already marked as
  // "I have this" during setup. Matched by exact label against this same
  // checklistTemplateFor() call — single source of truth, the wizard's own
  // preview list is generated by the identical function. Malformed/missing
  // input degrades to "nothing pre-checked," never an error.
  let availableLabels: Set<string>;
  try {
    const raw = String(formData.get("available_labels") ?? "[]");
    availableLabels = new Set(JSON.parse(raw));
  } catch {
    availableLabels = new Set();
  }

  const template = checklistTemplateFor(damage_category);
  if (template.length > 0) {
    const { error: checklistError } = await supabase.from("evidence_items").insert(
      template.map((item) => ({
        claim_id: data.id,
        user_id: user.id,
        label: item.label,
        category: item.category,
        checked: availableLabels.has(item.label),
      })),
    );
    if (checklistError) {
      console.error("createClaim: checklist seeding failed (non-fatal):", checklistError.message);
    }
  }

  // Returns the id rather than calling redirect() here: ClaimWizard.tsx
  // now invokes this directly from a client onSubmit handler (needed for
  // the category-gate error/duplicate-prompt UX, Decision #44), and
  // redirect()'s special throw doesn't compose safely with that call
  // site's own try/catch (it would be caught and misreported as a
  // failure). The client does the navigation instead. createClaim has no
  // other caller — safe to change this contract.
  return { id: data.id };
}

// Pre-flight check for ClaimWizard (Decision #44) — returns a plain JSON
// value, deliberately NOT a thrown Error: the "only .message survives"
// constraint (see checkUploadAccess's own comment) applies to thrown
// Errors crossing the Server Action boundary, not normal return values,
// and the wizard needs the full structured result to render the
// duplicate-claim prompt or the upgrade path, not just a message string.
// This is advisory only — createClaim always re-checks server-side before
// ever inserting a row, so a stale/bypassed client check here can never
// itself create an over-limit claim.
export async function checkClaimCategoryAccessAction(
  category: string,
): Promise<
  | { ok: false; error: string }
  | { ok: true; gate: ClaimCategoryGateResult; activeClaimId: string | null }
> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "Sign in required." };
  if (!isClaimCategory(category)) return { ok: false, error: "Unknown category." };

  const [gate, state] = await Promise.all([
    checkClaimCategoryAccess(supabase, user.id, category),
    getCategoryClaimState(supabase, user.id, category),
  ]);

  return { ok: true, gate, activeClaimId: state.activeClaimId };
}

// Decision #86 -- closes the free-tier bypass: a grader-converted claim is
// created with claim_category = null (from-grade/route.ts never asked the
// question), which made it invisible to checkClaimCategoryAccess's
// .eq("claim_category", category) filter. This is the one and only path
// that ever sets claim_category on such a claim, and it re-runs the exact
// same gate createClaim() enforces -- the moment a category is chosen is
// the moment this claim becomes subject to the free-tier rule, same as
// any wizard-created claim. .is("claim_category", null) in the update
// scope is a second, defense-in-depth guard: this action can only ever
// transition a claim from uncategorized, never silently recategorize an
// already-categorized one.
export async function setClaimCategory(
  claimId: string,
  category: string,
): Promise<
  | { ok: false; error: string }
  | { ok: true }
  | { ok: true; blocked: true; gate: Extract<ClaimCategoryGateResult, { allowed: false }> }
> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "Sign in required." };
  if (!isClaimCategory(category)) return { ok: false, error: "Unknown category." };

  const gate = await checkClaimCategoryAccess(supabase, user.id, category);
  if (!gate.allowed) {
    return { ok: true, blocked: true, gate };
  }

  const { error, count } = await supabase
    .from("claims")
    .update({ claim_category: category }, { count: "exact" })
    .eq("id", claimId)
    .eq("user_id", user.id)
    .is("claim_category", null);

  if (error) return { ok: false, error: error.message };
  if (!count) return { ok: false, error: "This claim already has a category, or you don't have access to it." };

  revalidatePath(`/claim/${claimId}`);
  return { ok: true };
}

// Claim lifecycle state (Decision #44). Deliberately unrestricted in
// either direction — no state machine — matching the founder's own
// "user-triggered, self-service" default for this proposed UI; the
// category-limit consequences live entirely in claimCategoryGate.ts, not
// here, so this action only ever needs to write the column.
export async function updateClaimStatus(claimId: string, status: string) {
  if (!isClaimStatus(status)) throw new Error("Unknown claim status.");

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { error } = await supabase
    .from("claims")
    .update({ status })
    .eq("id", claimId)
    .eq("user_id", user.id);
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
}

// Decision #75. The only path to setting/changing a claim's label after
// creation -- covers both a normal edit and a pre-#75 claim's first-ever
// label (those have label = NULL and show the created_at fallback, per the
// same table entry, until this is used).
export async function updateClaimLabel(claimId: string, label: string) {
  const trimmed = label.trim();
  if (!trimmed) throw new Error("Label can't be empty.");

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { error } = await supabase
    .from("claims")
    .update({ label: trimmed })
    .eq("id", claimId)
    .eq("user_id", user.id);
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
  revalidatePath("/claim");
  revalidatePath("/account");
}

export async function addEntry(claimId: string, formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const type = String(formData.get("type") ?? "note");
  const contact = String(formData.get("contact") ?? "").trim() || null;
  const summary = String(formData.get("summary") ?? "").trim();
  if (!summary) throw new Error("Entry needs a summary.");

  // Structured Communication Log (Documentation Coverage Gaps, 2026-07-25)
  // -- five optional fields, populated only when the new structured entry
  // types (Phone Call/Email/Text/Inspection/Voicemail) are used. The
  // original freeform types (call/visit/photo/letter/payment/note) submit
  // none of these and behave exactly as before.
  const contactTime = String(formData.get("contact_time") ?? "").trim() || null;
  const contactCompany = String(formData.get("contact_company") ?? "").trim() || null;
  const contactMethod = String(formData.get("contact_method") ?? "").trim() || null;
  const commitments = String(formData.get("commitments") ?? "").trim() || null;
  const followUpDateRaw = String(formData.get("follow_up_date") ?? "").trim();
  const followUpDate = followUpDateRaw || null;

  const { error } = await supabase.from("entries").insert({
    claim_id: claimId,
    user_id: user.id,
    type,
    contact,
    summary,
    contact_time: contactTime,
    contact_company: contactCompany,
    contact_method: contactMethod,
    commitments,
    follow_up_date: followUpDate,
  });
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
}

export async function addDeadline(claimId: string, formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const title = String(formData.get("title") ?? "").trim();
  const due_date = String(formData.get("due_date") ?? "").trim();
  if (!title || !due_date) throw new Error("Deadline needs a title and date.");

  const { error } = await supabase.from("deadlines").insert({
    claim_id: claimId,
    user_id: user.id,
    title,
    due_date,
  });
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
}

export async function addEvidenceItem(claimId: string, formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const label = String(formData.get("label") ?? "").trim();
  if (!label) throw new Error("Evidence item needs a label.");

  const { error } = await supabase.from("evidence_items").insert({
    claim_id: claimId,
    user_id: user.id,
    label,
  });
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
}

export async function toggleEvidenceItem(
  claimId: string,
  itemId: string,
  checked: boolean,
) {
  const supabase = await createClient();
  const { error } = await supabase
    .from("evidence_items")
    .update({ checked })
    .eq("id", itemId)
    .eq("claim_id", claimId);
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
}

const MAX_FILE_BYTES = 15 * 1024 * 1024; // 15MB — plenty for phone photos and scanned PDFs.

function kindForFile(file: File): "photo" | "pdf" | "doc" {
  if (file.type === "application/pdf") return "pdf";
  if (file.type.startsWith("image/")) return "photo";
  return "doc";
}

const KIND_LABEL: Record<ReturnType<typeof kindForFile>, string> = {
  photo: "Photo",
  pdf: "PDF",
  doc: "Document",
};

export async function uploadFile(
  claimId: string,
  evidenceItemId: string | null,
  formData: FormData,
  promisedItemId: string | null = null,
) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  // Step 6, item 2: confirm claim ownership before anything else. RLS
  // (auth.uid() = user_id on `claims`) already makes a mismatched claimId
  // return no row via this authenticated client — this makes the rejection
  // explicit rather than incidental, same reasoning as the Step 4 checkout
  // ownership check.
  const { data: claim, error: claimError } = await supabase
    .from("claims")
    .select("id")
    .eq("id", claimId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (claimError) throw new Error("Could not verify this claim. Try again.");
  if (!claim) throw new Error("You don't have access to this claim.");

  // File itself is validated first now (Decision #88 storage enforcement)
  // so its size is known before the gate runs -- the gate needs to check
  // "current usage + this file" against both the count and storage limits
  // in one pass, before anything touches Storage or the database.
  const file = formData.get("file");
  if (!(file instanceof File) || file.size === 0) {
    throw new Error("Choose a photo or PDF to upload.");
  }
  if (file.size > MAX_FILE_BYTES) {
    throw new Error("That file is larger than 15MB.");
  }
  if (!isAllowedUpload(file)) {
    throw new Error("That file type isn't supported. Upload a photo, PDF, or common document file.");
  }

  // Step 6 + Decision #88: free-tier file-count cap, then storage bytes.
  // Pro (any grant) skips the count check entirely (isPro() short-circuits,
  // same as before) but NOT the storage check -- Decision #81 gives Pro a
  // real 10GB + 500MB-buffer ceiling, not "unlimited," unlike uploads
  // themselves. Runs BEFORE the file is uploaded/inserted anywhere, so a
  // blocked attempt touches neither Storage nor the database.
  const gate = await checkUploadAccess(supabase, user.id, claimId, file.size);
  if (!gate.allowed) {
    if (gate.reason === "STORAGE_LIMIT_REACHED") {
      const limitLabel = gate.bindingLimit === "claim" ? "this claim's" : "your account's";
      throw new Error(
        gate.upgradeRequired
          ? `You've reached ${limitLabel} storage limit on the free plan. Upgrade to Pro for more space.`
          : `You've reached ${limitLabel} storage limit. Delete some files to free up space.`,
      );
    }
    throw new Error(
      `Free plan includes ${FREE_UPLOAD_LIMIT_PER_CLAIM} uploads per claim. Upgrade to Pro for unlimited uploads.`,
    );
  }

  const kind = kindForFile(file);

  // Before/After Photo Tags (Documentation Coverage Gaps, 2026-07-25) --
  // optional. Absent/empty stays untagged, exactly today's behavior. A
  // present-but-invalid value throws rather than silently dropping it --
  // defense in depth against a tampered form field, same pattern as
  // isClaimCategory elsewhere in this file.
  const evidenceStageRaw = formData.get("evidence_stage");
  let evidenceStage: string | null = null;
  if (typeof evidenceStageRaw === "string" && evidenceStageRaw.trim().length > 0) {
    if (!isEvidenceStage(evidenceStageRaw)) throw new Error("Invalid evidence stage.");
    evidenceStage = evidenceStageRaw;
  }

  const storagePath = `${user.id}/${claimId}/${crypto.randomUUID()}-${file.name}`;

  const { error: uploadError } = await supabase.storage
    .from("evidence")
    .upload(storagePath, file, {
      contentType: file.type || undefined,
    });
  if (uploadError) throw new Error(uploadError.message);

  // Don't trust the client-reported File.size as final (STORAGE_ENFORCEMENT_BRIEF.md's
  // explicit open design item) -- reconcile against what Storage actually
  // recorded for the object immediately after upload. Falls back to the
  // client-reported size only if the list lookup itself fails, rather than
  // blocking the upload over a metadata read.
  let sizeBytes = file.size;
  const folderPath = `${user.id}/${claimId}`;
  const objectName = storagePath.slice(folderPath.length + 1);
  const { data: listData } = await supabase.storage
    .from("evidence")
    .list(folderPath, { search: objectName });
  const actualSize = listData?.find((entry) => entry.name === objectName)?.metadata?.size;
  if (typeof actualSize === "number") sizeBytes = actualSize;

  const { data: fileRow, error: insertError } = await supabase
    .from("files")
    .insert({
      claim_id: claimId,
      user_id: user.id,
      storage_path: storagePath,
      kind,
      original_name: file.name,
      evidence_stage: evidenceStage,
      size_bytes: sizeBytes,
    })
    .select("id")
    .single();
  if (insertError || !fileRow) {
    await supabase.storage.from("evidence").remove([storagePath]);
    throw new Error(insertError?.message ?? "Could not save the upload.");
  }

  const { error: usageError } = await supabase.rpc("increment_storage_usage", {
    p_claim_id: claimId,
    p_user_id: user.id,
    p_delta_bytes: sizeBytes,
  });
  if (usageError) {
    // The file itself is already saved and usable -- a running-total miss
    // here is a drift bug to fix, not a reason to fail the whole upload
    // the user is waiting on.
    console.error("uploadFile: increment_storage_usage failed:", usageError.message);
  }

  if (promisedItemId) {
    // Promised-Document Tracker (2026-07-26) -- mutually exclusive with
    // evidenceItemId. Marks the promise received; statusForPromisedItem()
    // (src/lib/promisedItems.ts) derives "received" purely from file_id
    // being set, same derived-status philosophy as evidence_items.
    const { error: linkError } = await supabase
      .from("promised_items")
      .update({ file_id: fileRow.id })
      .eq("id", promisedItemId)
      .eq("claim_id", claimId);
    if (linkError) throw new Error(linkError.message);
  } else if (evidenceItemId) {
    const { error: linkError } = await supabase
      .from("evidence_items")
      .update({ file_id: fileRow.id, checked: true })
      .eq("id", evidenceItemId)
      .eq("claim_id", claimId);
    if (linkError) throw new Error(linkError.message);
  } else {
    // General Vault upload (CameraCapture, PendingPhotoUploader) — not tied
    // to an existing checklist row. Previously this left the file
    // completely unlinked from evidence_items, so it never moved the
    // Evidence score: scoreEvidence() (src/lib/claimHealth.ts) only reads
    // evidence_items, never `files` directly. Create a real checklist row
    // instead, labeled from what was actually uploaded — never an invented
    // description (Product Bible: "Never auto-generates entries the user
    // didn't make").
    const { error: createError } = await supabase.from("evidence_items").insert({
      claim_id: claimId,
      user_id: user.id,
      label: `${KIND_LABEL[kind]} — ${file.name}`,
      checked: false,
      file_id: fileRow.id,
    });
    if (createError) throw new Error(createError.message);
  }

  revalidatePath(`/claim/${claimId}`);
}

// Loss-of-Use Tracker (Roadmap Phase 1, Pro). Billing Build Order Step 5:
// rewritten to use isPro(claimId, userId) instead of a flat profiles.plan
// check — a lifetime entitlement on THIS claim now correctly unlocks the
// tracker for THIS claim, which the old plan-only check couldn't express
// at all (plan is account-wide, a lifetime unlock isn't). No free
// allowance (approved pricing model) — isPro only, same as Mold/Supplement.
// RLS only enforces ownership (auth.uid() = user_id), not entitlement,
// matching how every other table in this schema works — the entitlement
// check happens here, in the application layer, same boundary
// checkAiAccess/requireProAiAccess use for the AI tools. This remains the
// standard pattern every gate in the app follows.
async function requireProAccess(
  supabase: Awaited<ReturnType<typeof createClient>>,
  claimId: string,
  userId: string,
) {
  const pro = await isPro(supabase, claimId, userId);
  if (!pro) {
    throw new Error("Loss-of-Use Tracker is a Pro feature. Upgrade to log expenses.");
  }
}

export async function addLossOfUseExpense(claimId: string, formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  await requireProAccess(supabase, claimId, user.id);

  const date = String(formData.get("date") ?? "").trim();
  const category = String(formData.get("category") ?? "").trim();
  const amountRaw = String(formData.get("amount") ?? "").trim();
  const description = String(formData.get("description") ?? "").trim() || null;

  const amount = parseFloat(amountRaw);
  if (!date || !category || !amountRaw || Number.isNaN(amount) || amount < 0) {
    throw new Error("Expense needs a date, category, and a valid amount.");
  }

  const { error } = await supabase.from("loss_of_use_expenses").insert({
    claim_id: claimId,
    user_id: user.id,
    date,
    category,
    amount,
    description,
  });
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
}

export async function deleteLossOfUseExpense(claimId: string, expenseId: string) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { error } = await supabase
    .from("loss_of_use_expenses")
    .delete()
    .eq("id", expenseId)
    .eq("claim_id", claimId);
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
}

// Promised-Document Tracker (founder audit, 2026-07-26) -- tracks a
// carrier-side commitment ("they said the denial letter was coming") as
// distinct from evidence_items. No "mark received" action without a file:
// deliberately consistent with the rest of the app's evidence-backed-status
// philosophy (received means a file is actually attached, not just claimed).
export async function addPromisedItem(claimId: string, formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const description = String(formData.get("description") ?? "").trim();
  const promisedBy = String(formData.get("promised_by") ?? "").trim() || null;
  const targetDate = String(formData.get("target_date") ?? "").trim() || null;
  if (!description) throw new Error("Say what was promised.");

  const { error } = await supabase.from("promised_items").insert({
    claim_id: claimId,
    user_id: user.id,
    description,
    promised_by: promisedBy,
    target_date: targetDate,
  });
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
}

export async function deletePromisedItem(claimId: string, itemId: string) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { error } = await supabase
    .from("promised_items")
    .delete()
    .eq("id", itemId)
    .eq("claim_id", claimId);
  if (error) throw new Error(error.message);

  revalidatePath(`/claim/${claimId}`);
}

// Success Guarantee checklist (Decision #36, Billing Build Order Step 7 —
// eligibility foundation only, no refund trigger). Thin wrapper: auth,
// ownership, then the real logic in src/lib/guarantee.ts.
export async function toggleGuaranteeItem(claimId: string, itemKey: string, value: boolean) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { data: claim } = await supabase
    .from("claims")
    .select("id")
    .eq("id", claimId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!claim) throw new Error("You don't have access to this claim.");

  if (!isGuaranteeChecklistKey(itemKey)) throw new Error("Unknown checklist item.");

  await setGuaranteeChecklistItem(claimId, user.id, itemKey, value);
  await finalizeGuaranteeIfComplete(supabase, claimId, user.id);

  revalidatePath(`/claim/${claimId}`);
}

export async function deleteFile(
  claimId: string,
  fileId: string,
  storagePath: string,
) {
  const supabase = await createClient();

  // This IS the hard purge (removes both the Storage object and the row
  // together, in one step) -- Decision #52's soft-delete/hard-purge
  // distinction doesn't apply here since there's no separate unlink state
  // in this codebase; every call to deleteFile frees bytes immediately.
  // user_id read off the row itself (RLS on `files` already scopes it to
  // its owner) rather than a fresh auth.getUser() call.
  const { data: fileRow, error: fetchError } = await supabase
    .from("files")
    .select("size_bytes, user_id")
    .eq("id", fileId)
    .single();
  if (fetchError || !fileRow) throw new Error("Could not find that file.");

  const { error: storageError } = await supabase.storage
    .from("evidence")
    .remove([storagePath]);
  if (storageError) throw new Error(storageError.message);

  const { error } = await supabase.from("files").delete().eq("id", fileId);
  if (error) throw new Error(error.message);

  if (fileRow.size_bytes) {
    const { error: usageError } = await supabase.rpc("increment_storage_usage", {
      p_claim_id: claimId,
      p_user_id: fileRow.user_id,
      p_delta_bytes: -fileRow.size_bytes,
    });
    if (usageError) {
      console.error("deleteFile: increment_storage_usage failed:", usageError.message);
    }
  }

  revalidatePath(`/claim/${claimId}`);
}
