import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicPageHeader } from "@/app/_components/PublicPageHeader";
import { CHECKLISTS, getChecklist } from "@/lib/checklists";
import { UNIVERSAL_DISCLAIMER } from "@/lib/anthropic/outputFilter";

// One shared template for all 4 Emergency Checklists (Decision #96, spec
// section 2) -- "in-app version is the same content as a static checklist
// page, no new data model" per the spec's own instruction, driven by
// src/lib/checklists.ts so the in-app copy and the PDF (generated by
// 01_Brand/Emergency-Checklists/generate.js from the same JSON source)
// can't drift apart.

export function generateStaticParams() {
  return CHECKLISTS.map((c) => ({ slug: c.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const checklist = getChecklist(slug);
  if (!checklist) return { title: "Resource Library | WholeClaim" };
  return {
    title: `${checklist.title} | WholeClaim`,
    description: checklist.description,
  };
}

export default async function ChecklistPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const checklist = getChecklist(slug);
  if (!checklist) notFound();

  return (
    <main className="min-h-screen flex flex-col">
      <PublicPageHeader />

      <div className="max-w-2xl w-full mx-auto px-6 py-16">
        <Link href="/resources" className="text-xs font-semibold text-ledger mb-6 block">
          ← Resource Library
        </Link>

        <span className="block font-mono text-[0.65rem] font-semibold uppercase tracking-wider text-ledger">
          {checklist.eventType}
        </span>
        <h1 className="font-display text-2xl font-extrabold mt-1 mb-3">{checklist.title}</h1>
        <p className="text-sm text-ink/70 leading-relaxed mb-8">{checklist.description}</p>

        <a
          href={`/checklists/${checklist.pdfFile}`}
          download
          className="inline-flex items-center justify-center gap-2 border-2 border-hp-pine text-hp-pine hover:bg-hp-pine hover:text-white px-5 py-2.5 rounded-[10px] font-bold text-sm transition-colors mb-10"
        >
          Download PDF checklist
        </a>

        <div className="flex flex-col gap-8 mb-10">
          {checklist.groups.map((group) => (
            <div key={group.title}>
              <h2 className="font-mono text-xs font-semibold uppercase tracking-wider text-hp-stamp mb-3">
                {group.title}
              </h2>
              <ul className="flex flex-col gap-2">
                {group.items.map((item) => (
                  <li key={item} className="flex items-start gap-3 text-sm text-ink leading-relaxed">
                    <span
                      aria-hidden
                      className="mt-0.5 shrink-0 w-4 h-4 border-2 border-ink/40 rounded-[3px]"
                    />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="flex justify-center mb-8">
          <Link
            href="/grade"
            className="inline-flex items-center justify-center bg-hp-pine hover:bg-hp-pine-deep text-white px-6 py-3.5 rounded-[10px] font-bold text-sm transition-colors"
          >
            Check Your Claim Grade
          </Link>
        </div>

        <p className="text-xs text-ink/50 leading-relaxed border-t border-ink/10 pt-4">
          {UNIVERSAL_DISCLAIMER}
        </p>
      </div>
    </main>
  );
}
